### ISSUE TITLE
Segfault when uploading pictures to android device

### ISSUE THREAD

**Issue by asomers** [gphoto/gphoto2#212]
**Describe the bug**
When I try to upload a picture to an Android device, gphoto2 reliably segfaults

**Name the camera**
Google Inc Nexus/Pixel (PTP)   usb:000,007

**libgphoto2 and gphoto2 version**
gphoto2 2.5.15

Copyright (c) 2000-2017 Lutz Mueller and others

gphoto2 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of gphoto2 under the terms of the GNU General Public
License. For more information about these matters, see the files named COPYING.

This version of gphoto2 is using the following software versions and options:
gphoto2         2.5.15         cc, popt(m), exif, no cdk, aa, jpeg, readline
libgphoto2      2.5.16         all camlibs, cc, no ltdl, EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip usb1 usbdiskdirect usbscsi, cc, no ltdl, USB, no serial

**To Reproduce**
1. Connect Android device via USB
2. Click "USB Charging", and in the menu that pops up, select either "File transfers" or "Photo transfer (PTP).  The bug affects both modes.
3. touch empty.txt
4. gphoto2 -f /store_00010001/Pictures -u empty.txt

A segfault results.  Here is the stack trace:
```
#0  strlen (str=0x9c52b0 <error: Cannot access memory at address 0x9c52b0>)
    at /usr/src/lib/libc/string/strlen.c:101
#1  0x00000008011df6a4 in ?? () from /usr/local/lib/libgphoto2/2.5.16/ptp2.so
#2  0x00000008011df2b4 in ?? () from /usr/local/lib/libgphoto2/2.5.16/ptp2.so
#3  0x0000000801208891 in ?? () from /usr/local/lib/libgphoto2/2.5.16/ptp2.so
#4  0x000000080028ba25 in gp_filesystem_put_file ()
   from /usr/local/lib/libgphoto2.so.6
#5  0x00000008002852c8 in gp_camera_folder_put_file ()
   from /usr/local/lib/libgphoto2.so.6
#6  0x000000000020c95a in ?? ()
#7  0x00000000002183b2 in ?? ()
#8  0x00000008004d5287 in ?? () from /usr/local/lib/libpopt.so.0
#9  0x00000008004d5216 in ?? () from /usr/local/lib/libpopt.so.0
#10 0x00000008004d3b37 in poptGetNextOpt () from /usr/local/lib/libpopt.so.0
#11 0x0000000000217db4 in ?? ()
#12 0x000000000020c11b in ?? ()
#13 0x0000000800246000 in ?? ()
#14 0x0000000000000000 in ?? ()
```
ktrace shows the following sequence repeated many times just before the segfault:
```
 10294 gphoto2  CALL  ioctl(0x7,USB_FS_START,0x7fffffffb550)
 10294 gphoto2  RET   ioctl 0
 10294 gphoto2  CALL  poll(0x7fffffffb550,0x2,0xffffffff)
 10294 gphoto2  RET   poll 1
 10294 gphoto2  CALL  read(0x3,0x7fffffffb58f,0x1)
 10294 gphoto2  RET   read -1 errno 35 Resource temporarily unavailable
 10294 gphoto2  CALL  ioctl(0x7,USB_FS_COMPLETE,0x7fffffffb4f8)
 10294 gphoto2  RET   ioctl 0
 10294 gphoto2  CALL  ioctl(0x7,USB_FS_COMPLETE,0x7fffffffb4f8)
 10294 gphoto2  RET   ioctl -1 errno 16 Device busy
```

I'm guessing that the bug happens in an error path, and has something to do with the filename, because if I specify a filename with `--filename` then I get a different error but no segfault
```
> gphoto2 -f /store_00010001/Pictures --filename empty2.txt -u empty.txt
                                                                               
*** Error ***              
PTP General Error
*** Error (-1: 'Unspecified error') ***       

For debugging messages, please use the --debug option.
Debugging messages may help finding a solution to your problem.
If you intend to send any error or debug messages to the gphoto
developer mailing list <gphoto-devel@lists.sourceforge.net>, please run
gphoto2 as follows:

    env LANG=C gphoto2 --debug --debug-logfile=my-logfile.txt -f /store_00010001/Pictures --filename empty2.txt -u empty.txt

Please make sure there is sufficient quoting around the arguments.
```

**Comment by msmeissn** [comment]
I cant get my Samsung S7 to crash ... I always get PTP General Error, with libgphoto2 2.5.22.

could you test a newer libgphoto2 ?

or can you install debugging symbols of libgphoto2 for the backtrace?

and/or also append  --debug --debug-logfile=upload.log   and attach upload.log for such a crash

**Comment by asomers** [comment]
I get the same error with gphoto2-2.5.20.  Here is a backtrace from a debug build:
```
#0  strcmp () at /usr/src/lib/libc/amd64/string/strcmp.S:48
48	/usr/src/lib/libc/amd64/string/strcmp.S: No such file or directory.
(gdb) bt
#0  strcmp () at /usr/src/lib/libc/amd64/string/strcmp.S:48
#1  0x00000008012ccbf3 in find_child (params=0x80103f000, 
    file=0x9de2b0 <error: Cannot access memory at address 0x9de2b0>, 
    storage=65537, handle=6, retob=0x0) at ptp2/library.c:6497
#2  0x00000008012c8ac4 in put_file_func (fs=0x80100a000, 
    folder=0x8009da040 "/store_00010001/Pictures", 
    filename=0x9de2b0 <error: Cannot access memory at address 0x9de2b0>, 
    type=GP_FILE_TYPE_NORMAL, file=0x801036000, data=0x8009d7030, 
    context=0x80100a0a0) at ptp2/library.c:7597
#3  0x00000008002a0309 in gp_filesystem_put_file (fs=0x80100a000, 
    folder=0x8009da040 "/store_00010001/Pictures", 
    filename=0x9de2b0 <error: Cannot access memory at address 0x9de2b0>, 
    type=GP_FILE_TYPE_NORMAL, file=0x801036000, context=0x80100a0a0)
    at gphoto2-filesys.c:1313
#4  0x0000000800295d73 in gp_camera_folder_put_file (camera=0x8009d7030, 
    folder=0x8009da040 "/store_00010001/Pictures", 
    filename=0x9de2b0 <error: Cannot access memory at address 0x9de2b0>, 
    type=GP_FILE_TYPE_NORMAL, file=0x801036000, context=0x80100a0a0)
    at gphoto2-camera.c:1559
#5  0x000000000020ce37 in action_camera_upload_file (p=0x22a008 <gp_params>, 
    folder=0x8009da040 "/store_00010001/Pictures", 
    path=0x8009de2b0 "empty.txt") at actions.c:107
#6  0x00000000002222fd in cb_arg_run (ctx=0x80101e000, 
    reason=POPT_CALLBACK_REASON_OPTION, opt=0x7fffffffb8b0, 
    arg=0x8009de2b0 "empty.txt", params=0x7fffffffc3b8) at main.c:1757
#7  0x0000000000220ba2 in cb_arg (ctx=0x80101e000, 
    reason=POPT_CALLBACK_REASON_OPTION, opt=0x7fffffffb8b0, 
    arg=0x8009de2b0 "empty.txt", data=0x7fffffffc3b8) at main.c:1863
#8  0x00000008004ee287 in ?? () from /usr/local/lib/libpopt.so.0
#9  0x00000008004ee216 in ?? () from /usr/local/lib/libpopt.so.0
#10 0x00000008004ecb37 in poptGetNextOpt () from /usr/local/lib/libpopt.so.0
#11 0x0000000000220579 in main (argc=5, argv=0x7fffffffeae0, 
    envp=0x7fffffffeb10) at main.c:2512
```
And here's the debug log: https://gist.github.com/asomers/3b35360434da00b1273b2cd7f576ac79
