### ISSUE TITLE
Sony Alpha 5100 munmap_chunk(): invalid pointer

### ISSUE THREAD

**Issue by gonzalobg** [gphoto/gphoto2#493]
This (am using arch linux gphoto2-git package):

```
gphoto2 --version 
gphoto2 2.5.28.1

gphoto2 --stdout --capture-movie
```

crashes with (gdb backtrace):

```
gdb --args gphoto2 --stdout --capture-movie
GNU gdb (GDB) 11.2
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from gphoto2...
(No debugging symbols found in gphoto2)
(gdb) r
Starting program: /usr/bin/gphoto2 --stdout --capture-movie
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff756e640 (LWP 1262981)]
[Thread 0x7ffff756e640 (LWP 1262981) exited]
[New Thread 0x7ffff756e640 (LWP 1262984)]
[Thread 0x7ffff756e640 (LWP 1262984) exited]
[New Thread 0x7ffff756e640 (LWP 1262999)]
[Thread 0x7ffff756e640 (LWP 1262999) exited]
[New Thread 0x7ffff756e640 (LWP 1263015)]
[Thread 0x7ffff756e640 (LWP 1263015) exited]
[New Thread 0x7ffff756e640 (LWP 1263016)]
[Thread 0x7ffff756e640 (LWP 1263016) exited]
[New Thread 0x7ffff756e640 (LWP 1263017)]
[Thread 0x7ffff756e640 (LWP 1263017) exited]
[New Thread 0x7ffff756e640 (LWP 1263018)]
[Thread 0x7ffff756e640 (LWP 1263018) exited]
[New Thread 0x7ffff756e640 (LWP 1263019)]
[Thread 0x7ffff756e640 (LWP 1263019) exited]
[New Thread 0x7ffff756e640 (LWP 1263020)]
[Thread 0x7ffff756e640 (LWP 1263020) exited]
[New Thread 0x7ffff756e640 (LWP 1263021)]
Capturing preview frames as movie to 'stdout'. Press Ctrl-C to abort.
munmap_chunk(): invalid pointer

Thread 1 "gphoto2" received signal SIGABRT, Aborted.
0x00007ffff7c5634c in __pthread_kill_implementation () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7c5634c in __pthread_kill_implementation () from /usr/lib/libc.so.6
#1  0x00007ffff7c094b8 in raise () from /usr/lib/libc.so.6
#2  0x00007ffff7bf3534 in abort () from /usr/lib/libc.so.6
#3  0x00007ffff7c4a397 in __libc_message () from /usr/lib/libc.so.6
#4  0x00007ffff7c6033c in malloc_printerr () from /usr/lib/libc.so.6
#5  0x00007ffff7c6062c in munmap_chunk () from /usr/lib/libc.so.6
#6  0x00007ffff7c64c2a in free () from /usr/lib/libc.so.6
#7  0x00007ffff6ca8b5e in ?? () from /usr/lib/libgphoto2/2.5.28/ptp2.so
#8  0x00007ffff7f44ef5 in gp_camera_capture_preview () from /usr/lib/libgphoto2.so.6
#9  0x00005555555616de in ?? ()
#10 0x00005555555697c4 in ?? ()
#11 0x00007ffff7dd4858 in ?? () from /usr/lib/libpopt.so.0
#12 0x00007ffff7dd48e6 in ?? () from /usr/lib/libpopt.so.0
#13 0x00007ffff7dd8c50 in poptGetNextOpt () from /usr/lib/libpopt.so.0
#14 0x000055555555c3d1 in ?? ()
#15 0x00007ffff7bf4310 in __libc_start_call_main () from /usr/lib/libc.so.6
#16 0x00007ffff7bf43c1 in __libc_start_main_impl () from /usr/lib/libc.so.6
#17 0x000055555555d4c5 in ?? ()
```

**Describe the bug**

This used not to crash, but now it crashes. 

**Name the camera**

```
Model                          Port
----------------------------------------------------------
Sony Alpha-A5100 (Control)     usb:001,036
```

**To Reproduce**

Run

```
gphoto2 --stdout --capture-movie 
```

**Comment by msmeissn** [comment]
can you try current GIT of libgphoto2?

**Comment by gonzalobg** [comment]
Just tried, but get different errors each time:

```
+ gphoto2 --stdout --capture-movie |ffmpeg -i - -vcodec rawvideo -pix_fmt yuv420p -threads 0 -f v4l2 /dev/video4
ffmpeg version n5.0 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
Capturing preview frames as movie to 'stdout'. Press Ctrl-C to abort.
free(): invalid pointer
pipe:: Invalid data found when processing input
```

or 

```
munmap_chunk(): invalid pointer
pipe:: Invalid data found when processing input
```

**Comment by msmeissn** [comment]
can you run this under valgrind?

valgrind gphoto2 --capture-movie=1s

**Comment by gonzalobg** [comment]
```
==48725== Memcheck, a memory error detector
==48725== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==48725== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==48725== Command: gphoto2 --capture-movie=1s
==48725==
Capturing preview frames as movie to 'movie.mjpg' for 1 seconds.
==48725== Conditional jump or move depends on uninitialised value(s)
==48725==    at 0x4848235: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==48725==    by 0x5F0A282: ??? (in /usr/lib/libgphoto2/2.5.29.1/ptp2.so)
==48725==    by 0x5F21418: ??? (in /usr/lib/libgphoto2/2.5.29.1/ptp2.so)
==48725==    by 0x486C680: gp_camera_capture_preview (in /usr/lib/libgphoto2.so.6.2.0)
==48725==    by 0x1156DD: ??? (in /usr/bin/gphoto2)
==48725==    by 0x11D7C3: ??? (in /usr/bin/gphoto2)
==48725==    by 0x4A43857: ??? (in /usr/lib/libpopt.so.0.0.1)
==48725==    by 0x4A438E5: ??? (in /usr/lib/libpopt.so.0.0.1)
==48725==    by 0x4A47C4F: poptGetNextOpt (in /usr/lib/libpopt.so.0.0.1)
==48725==    by 0x1103D0: ??? (in /usr/bin/gphoto2)
==48725==    by 0x4A7C30F: (below main) (in /usr/lib/libc.so.6)
==48725==
==48725== Invalid free() / delete / delete[] / realloc()
==48725==    at 0x484827F: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==48725==    by 0x5F0A282: ??? (in /usr/lib/libgphoto2/2.5.29.1/ptp2.so)
==48725==    by 0x5F21418: ??? (in /usr/lib/libgphoto2/2.5.29.1/ptp2.so)
==48725==    by 0x486C680: gp_camera_capture_preview (in /usr/lib/libgphoto2.so.6.2.0)
==48725==    by 0x1156DD: ??? (in /usr/bin/gphoto2)
==48725==    by 0x11D7C3: ??? (in /usr/bin/gphoto2)
==48725==    by 0x4A43857: ??? (in /usr/lib/libpopt.so.0.0.1)
==48725==    by 0x4A438E5: ??? (in /usr/lib/libpopt.so.0.0.1)
==48725==    by 0x4A47C4F: poptGetNextOpt (in /usr/lib/libpopt.so.0.0.1)
==48725==    by 0x1103D0: ??? (in /usr/bin/gphoto2)
==48725==    by 0x4A7C30F: (below main) (in /usr/lib/libc.so.6)
==48725==  Address 0x1ffeffc2b3 is on thread 1's stack
==48725==
==48725== Conditional jump or move depends on uninitialised value(s)
==48725==    at 0x4848235: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==48725==    by 0x5F0A294: ??? (in /usr/lib/libgphoto2/2.5.29.1/ptp2.so)
==48725==    by 0x5F21418: ??? (in /usr/lib/libgphoto2/2.5.29.1/ptp2.so)
==48725==    by 0x486C680: gp_camera_capture_preview (in /usr/lib/libgphoto2.so.6.2.0)
==48725==    by 0x1156DD: ??? (in /usr/bin/gphoto2)
==48725==    by 0x11D7C3: ??? (in /usr/bin/gphoto2)
==48725==    by 0x4A43857: ??? (in /usr/lib/libpopt.so.0.0.1)
==48725==    by 0x4A438E5: ??? (in /usr/lib/libpopt.so.0.0.1)
==48725==    by 0x4A47C4F: poptGetNextOpt (in /usr/lib/libpopt.so.0.0.1)
==48725==    by 0x1103D0: ??? (in /usr/bin/gphoto2)
==48725==    by 0x4A7C30F: (below main) (in /usr/lib/libc.so.6)
==48725==
==48725== Invalid free() / delete / delete[] / realloc()
==48725==    at 0x484827F: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==48725==    by 0x5F0A294: ??? (in /usr/lib/libgphoto2/2.5.29.1/ptp2.so)
==48725==    by 0x5F21418: ??? (in /usr/lib/libgphoto2/2.5.29.1/ptp2.so)
==48725==    by 0x486C680: gp_camera_capture_preview (in /usr/lib/libgphoto2.so.6.2.0)
==48725==    by 0x1156DD: ??? (in /usr/bin/gphoto2)
==48725==    by 0x11D7C3: ??? (in /usr/bin/gphoto2)
==48725==    by 0x4A43857: ??? (in /usr/lib/libpopt.so.0.0.1)
==48725==    by 0x4A438E5: ??? (in /usr/lib/libpopt.so.0.0.1)
==48725==    by 0x4A47C4F: poptGetNextOpt (in /usr/lib/libpopt.so.0.0.1)
==48725==    by 0x1103D0: ??? (in /usr/bin/gphoto2)
==48725==    by 0x4A7C30F: (below main) (in /usr/lib/libc.so.6)
==48725==  Address 0x61133da7d69eeb00 is not stack'd, malloc'd or (recently) free'd
==48725==
ERROR: Movie capture error... Exiting.
Movie capture finished (0 frames)
==48725==
==48725== HEAP SUMMARY:
==48725==     in use at exit: 153,832 bytes in 47 blocks
==48725==   total heap usage: 84,754 allocs, 84,709 frees, 111,696,782 bytes allocated
==48725==
==48725== LEAK SUMMARY:
==48725==    definitely lost: 45,184 bytes in 4 blocks
==48725==    indirectly lost: 0 bytes in 0 blocks
==48725==      possibly lost: 0 bytes in 0 blocks
==48725==    still reachable: 108,632 bytes in 42 blocks
==48725==         suppressed: 16 bytes in 1 blocks
==48725== Rerun with --leak-check=full to see details of leaked memory
==48725==
==48725== Use --track-origins=yes to see where uninitialised values come from
==48725== For lists of detected and suppressed errors, rerun with: -s
==48725== ERROR SUMMARY: 4 errors from 4 contexts (suppressed: 0 from 0)```

**Comment by gonzalobg** [comment]
If I build libgphoto2-git with "-O0 -g3" then I get: 

```
Capturing preview frames as movie to 'movie.mjpg' for 1 seconds.

*** Error ***
PTP Timeout

*** Error ***
An error occurred in the io-library ('Timeout reading from or writing to the port'): No error description available
ERROR: Movie capture error... Exiting.
Movie capture finished (0 frames)
```

when running normally, and this when running with valgrind:

```
==247918== Memcheck, a memory error detector
==247918== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==247918== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==247918== Command: gphoto2 --capture-movie=1s
==247918==
Capturing preview frames as movie to 'movie.mjpg' for 1 seconds.

*** Error ***
PTP Timeout

*** Error ***
An error occurred in the io-library ('Timeout reading from or writing to the port'): No error description available
ERROR: Movie capture error... Exiting.
Movie capture finished (0 frames)
==247918==
==247918== HEAP SUMMARY:
==247918==     in use at exit: 220,032 bytes in 53 blocks
==247918==   total heap usage: 84,561 allocs, 84,508 frees, 111,677,545 bytes allocated
==247918==
==247918== LEAK SUMMARY:
==247918==    definitely lost: 45,864 bytes in 5 blocks
==247918==    indirectly lost: 65,520 bytes in 5 blocks
==247918==      possibly lost: 0 bytes in 0 blocks
==247918==    still reachable: 108,632 bytes in 42 blocks
==247918==         suppressed: 16 bytes in 1 blocks
==247918== Rerun with --leak-check=full to see details of leaked memory
==247918==
==247918== For lists of detected and suppressed errors, rerun with: -s
==247918== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Comment by msmeissn** [comment]
i put in another fix into GIT to avoid this crash. can you check ahaon

**Comment by gonzalobg** [comment]
Thanks! The crash is gone!

Now I get: 

```*** Error ***
PTP Timeout

*** Error ***
An error occurred in the io-library ('Timeout reading from or writing to the port'): No error description available
ERROR: Movie capture error... Exiting.
Movie capture finished (0 frames)
```

But I think this is a different issue. Is there a chat channel for help with libgphoto / gphoto2?

**Comment by msmeissn** [comment]
I am on libera.chat #gphoto   channel, but usually very idle.  ;)
