### ISSUE TITLE
capture-movie to stdout->segmentation fault

### ISSUE THREAD

**Issue by sasa00** [gphoto/gphoto2#91]
Hello,

I'm trying to show a live preview over stdout to omxplayer, like described on several sites(e.g.: [Example](https://www.raspberrypi.org/forums/viewtopic.php?f=91&t=80611))
My test is:
```
mkfifo fifo.mjpg
gphoto2 --capture-movie --stdout> fifo.mjpg &
omxplayer fifo.mjpg
```

I always get a segmentation fault:

```
~ $ gphoto2 --capture-movie --stdout> fifo.mjpg
Capturing preview frames as movie to 'stdout'. Press Ctrl-C to abort.
Segmentation fault
```
Even if I try:
`gphoto2 --capture-movie`
I get this error

My gphoto2 version is:
```
photo2 2.5.14

Copyright (c) 2000-2016 Lutz Mueller and others

gphoto2 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of gphoto2 under the terms of the GNU General Public
License. For more information about these matters, see the files named COPYING.

This version of gphoto2 is using the following software versions and options:
gphoto2         2.5.14         gcc, popt(m), exif, no cdk, no aa, no jpeg, no readline
libgphoto2      2.5.4          all camlibs, gcc, ltdl, EXIF
libgphoto2_port 0.12.0         gcc, ltdl, USB, serial without locking
```
My DSLR is a Canon EOS 450D and is connected via USB to a Raspberry 3.

Do you have an idea whats going on? Am I missing something or did I find a bug?

**Comment by msmeissn** [comment]
This should not happen. Will try this out later...

**Comment by msmeissn** [comment]
hmm. does nopt happen here. 

cazn you run gphoto2 in gdb and get the backtrace?

**Comment by sasa00** [comment]
Hi,

sorry for my late answer. I was on holiday ;-)
I never worked with gdb before, so this is what I did:


```
gdb --args gphoto2 --capture-movie --stdout

run
```

here's what I got:

 ```
  ֻ��N+}ϟ�k�/k&s��Ųw|�O��֮6��� �IQ�z��`����>cVu9�����?�
Program received signal SIGSEGV, Segmentation fault.
__strchrnul (
    s=s@entry=0x2578b <error: Cannot access memory at address 0x2578b>, 
    c_in=c_in@entry=37) at strchrnul.c:52
52	strchrnul.c: No such file or directory.

```
running 'bt' gives:

```
(gdb) bt
#0  __strchrnul (
    s=s@entry=0x2578b <error: Cannot access memory at address 0x2578b>, 
    c_in=c_in@entry=37) at strchrnul.c:52
#1  0x76cd4cec in __find_specmb (
    format=0x2578b <error: Cannot access memory at address 0x2578b>)
    at printf-parse.h:108
#2  _IO_vfprintf_internal (s=s@entry=0x7effc788, 
    format=format@entry=0x2578b <error: Cannot access memory at address 0x2578b>, ap=ap@entry=...) at vfprintf.c:1315
#3  0x76cfd75c in _IO_vsnprintf (string=0x7effc830 "", string@entry=0x0, 
    maxlen=<optimized out>, maxlen@entry=0, 
    format=format@entry=0x2578b <error: Cannot access memory at address 0x2578b>, args=args@entry=...) at vsnprintf.c:119
#4  0x76f04a88 in gpi_vsnprintf (
    format=0x2578b <error: Cannot access memory at address 0x2578b>, 
    format@entry=0x0, args=..., args@entry=...) at gphoto2-port-log.c:116
#5  0x76f04e38 in gp_log_data (
    domain=0xc <error: Cannot access memory at address 0xc>, 
    data=0xae1bb "\f", size=1996351940, 
    format=0x2578b <error: Cannot access memory at address 0x2578b>)
    at gphoto2-port-log.c:216
#6  0x76219bc8 in ?? ()
   from /usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.4/ptp2.so
---Type <return> to continue, or q <return> to quit---
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) 
```

**Comment by sasa00** [comment]
I think I found the problem:
![grafik](https://user-images.githubusercontent.com/5843305/30006878-f9cfc968-9102-11e7-835d-30697295ca47.png)
I had different version of gphoto and libgphoto running. I removed the libgphoto installed via apt-get and afterwards the OS is using the self compiled version .14.

**Comment by msmeissn** [comment]
And did it work afterwards?

**Comment by sasa00** [comment]
Yes! Forget to mention that...

**Comment by msmeissn** [comment]
thanks! its likely there was a bug that got fixed inbetween ;)
